/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

export * from "./ProgramService";
export * from "./ProgramsService";
export * from "./program";
