/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import { AxiosInstance, AxiosRequestConfig } from "axios";
import { ProgramList } from "../../interfaces";

export class ProgramsService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  /**
   * @param x-gw-ims-org-id IMS organization ID that the request is being made under.
   * @param Authorization Bearer [token] - An access token for the technical account created through integration with Adobe IO
   * @param x-api-key IMS Client ID (API Key) which is subscribed to consume services on console.adobe.io
   */
  getPrograms = async (): Promise<ProgramList> => {
    const config: AxiosRequestConfig = {
      method: "get",
      url: "/api/programs"
    };
    const response = await this.apiClient.request<ProgramList>(config);
    return response.data;
  };
}
