/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {RepositoryBranch} from './RepositoryBranch';
import {HalLink} from './HalLink';

export interface BranchList {
  _totalNumberOfItems?: number;
  readonly _embedded?: {branches?: Array<RepositoryBranch>};
  readonly _links?: {next?: HalLink; prev?: HalLink; self?: HalLink};
}
