/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {HalLink} from './HalLink';

export interface EmbeddedProgram {
  readonly id?: string;
  name: string;
  readonly enabled?: boolean;
  readonly tenantId?: string;
  readonly _links?: {self?: HalLink};
}
