/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import { Environment } from "./Environment";
import { HalLink } from "./HalLink";

export interface EnvironmentList {
  _totalNumberOfItems?: number;
  readonly _embedded?: { environments?: Array<Environment> };
  readonly _links?: { next?: HalLink; prev?: HalLink; self?: HalLink };
}
