/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {HalLink} from './HalLink';

export interface Environment {
  readonly id?: string;
  readonly programId?: string;
  name?: string;
  description?: string;
  type?: string;
  readonly _links?: {
    http___ns_adobe_com_adobecloud_rel_program?: HalLink;
    http___ns_adobe_com_adobecloud_rel_pipeline?: HalLink;
    http___ns_adobe_com_adobecloud_rel_author?: HalLink;
    http___ns_adobe_com_adobecloud_rel_publish?: HalLink;
    self?: HalLink;
  };
}
