/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

export interface HalLink {
  href?: string;
  templated?: boolean;
  type?: string;
  deprecation?: string;
  profile?: string;
  title?: string;
  hreflang?: string;
  name?: string;
}
