/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

export interface Metric {
  id?: string;
  severity?: string;
  passed?: boolean;
  override?: boolean;
  actualValue?: string;
  expectedValue?: string;
  comparator?: string;
  kpi?: string;
}
