/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {PipelinePhase} from './PipelinePhase';
import {HalLink} from './HalLink';

export interface Pipeline {
  id?: string;
  programId?: string;
  name: string;
  trigger?: string;
  status?: string;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  readonly lastStartedAt?: string;
  readonly lastFinishedAt?: string;
  phases: Array<PipelinePhase>;
  readonly _links?: {
    http___ns_adobe_com_adobecloud_rel_program?: HalLink;
    http___ns_adobe_com_adobecloud_rel_execution?: HalLink;
    http___ns_adobe_com_adobecloud_rel_executions?: HalLink;
    self?: HalLink;
  };
}
