/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import { RequestedPageDetails } from "./RequestedPageDetails";
import { PipelineExecution } from "./PipelineExecution";
import { HalLink } from "./HalLink";

export interface PipelineExecutionListRepresentation {
  _totalNumberOfItems?: number;
  _page?: RequestedPageDetails;
  readonly _embedded?: { executions?: Array<PipelineExecution> };
  readonly _links?: {
    next?: HalLink;
    page?: HalLink;
    prev?: HalLink;
    self?: HalLink;
  };
}
