/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

export interface PipelinePhase {
  name?: string;
  type: string;
  repositoryId?: string;
  branch?: string;
  environmentId?: string;
}
