/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import { HalLink } from "./HalLink";

export interface PipelineExecutionStepState {
  id?: string;
  stepId?: string;
  phaseId?: string;
  action?: string;
  repository?: string;
  branch?: string;
  environment?: string;
  environmentType?: string;
  startedAt?: string;
  finishedAt?: string;
  details?: {};
  status?: string;
  readonly _links?: {
    http___ns_adobe_com_adobecloud_rel_execution?: HalLink;
    http___ns_adobe_com_adobecloud_rel_pipeline?: HalLink;
    http___ns_adobe_com_adobecloud_rel_pipeline_logs?: HalLink;
    http___ns_adobe_com_adobecloud_rel_pipeline_metrics?: HalLink;
    http___ns_adobe_com_adobecloud_rel_pipeline_advance?: HalLink;
    http___ns_adobe_com_adobecloud_rel_pipeline_cancel?: HalLink;
    http___ns_adobe_com_adobecloud_rel_program?: HalLink;
    self?: HalLink;
  };
}
