/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import { Metric } from "./Metric";

export interface PipelineStepMetrics {
  readonly metrics?: Array<Metric>;
}
