/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {HalLink} from './HalLink';

export interface Program {
  readonly id?: string;
  name: string;
  enabled?: boolean;
  tenantId?: string;
  imsOrgId?: string;
  readonly _links?: {
    http___ns_adobe_com_adobecloud_rel_pipelines?: HalLink;
    http___ns_adobe_com_adobecloud_rel_environments?: HalLink;
    http___ns_adobe_com_adobecloud_rel_repositories?: HalLink;
    self?: HalLink;
  };
}
