/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import { EmbeddedProgram } from "./EmbeddedProgram";
import { HalLink } from "./HalLink";

export interface ProgramList {
  _totalNumberOfItems?: number;
  readonly _embedded?: { programs?: Array<EmbeddedProgram> };
  readonly _links?: { next?: HalLink; prev?: HalLink; self?: HalLink };
}
