/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import { Repository } from "./Repository";
import { HalLink } from "./HalLink";

export interface RepositoryList {
  _totalNumberOfItems?: number;
  readonly _embedded?: { repositories?: Array<Repository> };
  readonly _links?: { next?: HalLink; prev?: HalLink; self?: HalLink };
}
