/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import {HalLink} from './HalLink';

export interface RepositoryBranch {
  programId?: string;
  repositoryId?: number;
  name?: string;
  readonly _links?: {
    http___ns_adobe_com_adobecloud_rel_program?: HalLink;
    http___ns_adobe_com_adobecloud_rel_repository?: HalLink;
  };
}
