/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

export interface RequestedPageDetails {
  limit?: number;
  orderBy?: string;
  property?: Array<string>;
  type?: string;
  next?: number;
  prev?: number;
}
