/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import { AxiosInstance, AxiosRequestConfig } from "axios";
import { PipelineExecutionListRepresentation } from "../../../interfaces";

export class ExecutionsService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  /**
   * @param programId Identifier of the program.
   * @param pipelineId Identifier of the pipeline
   * @param start Pagination start parameter
   * @param limit Pagination limit parameter
   * @param x-gw-ims-org-id IMS organization ID that the request is being made under.
   * @param Authorization Bearer [token] - An access token for the technical account created through integration with Adobe IO
   * @param x-api-key IMS Client ID (API Key) which is subscribed to consume services on console.adobe.io
   */
  getExecutions = async (
    programId: string,
    pipelineId: string,
    params?: {
      start?: string;
      limit?: number;
    }
  ): Promise<PipelineExecutionListRepresentation> => {
    const config: AxiosRequestConfig = {
      method: "get",
      params,
      url: `/api/program/${programId}/pipeline/${pipelineId}/executions`
    };
    const response = await this.apiClient.request<
      PipelineExecutionListRepresentation
    >(config);
    return response.data;
  };
}
