/* tslint:disable */

/**
 * This file was automatically generated by "Swaxios".
 * It should not be modified by hand.
 */

import { AxiosInstance, AxiosRequestConfig } from "axios";
import { PipelineList } from "../../../interfaces";

export class PipelinesService {
  private readonly apiClient: AxiosInstance;

  constructor(apiClient: AxiosInstance) {
    this.apiClient = apiClient;
  }

  /**
   * @param programId Identifier of the program
   * @param x-gw-ims-org-id IMS organization ID that the request is being made under.
   * @param Authorization Bearer [token] - An access token for the technical account created through integration with Adobe IO
   * @param x-api-key IMS Client ID (API Key) which is subscribed to consume services on console.adobe.io
   */
  getPipelines = async (programId: string): Promise<PipelineList> => {
    const config: AxiosRequestConfig = {
      method: "get",
      url: `/api/program/${programId}/pipelines`
    };
    const response = await this.apiClient.request<PipelineList>(config);
    return response.data;
  };
}
